# Generated by Django 3.2.9 on 2023-02-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('wybor', models.IntegerField(choices=[(38, 'Male1'), (39, 'Male2'), (40, 'Srednie1'), (41, 'Srednie2'), (42, 'Duze1'), (43, 'Duze2')])),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentarz', models.TextField()),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.przedmiot')),
            ],
        ),
    ]
