# Generated by Django 3.2.9 on 2023-02-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('wybor', models.IntegerField(choices=[(38, 'Male1'), (39, 'Male2'), (40, 'Srednie1'), (41, 'Srednie2'), (42, 'Duze1'), (43, 'Duze2')], default=40)),
            ],
        ),
        migrations.AlterField(
            model_name='ocena',
            name='przedmiot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.buty'),
        ),
        migrations.DeleteModel(
            name='Przedmiot',
        ),
    ]
