# Generated by Django 3.2.9 on 2023-02-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0002_auto_20230220_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='buty',
            name='Wyglad',
            field=models.ImageField(default=2, upload_to='static'),
            preserve_default=False,
        ),
    ]
