# Generated by Django 3.2.9 on 2023-02-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0003_buty_wyglad'),
    ]

    operations = [
        migrations.AddField(
            model_name='buty',
            name='Marka',
            field=models.TextField(default='Nike'),
        ),
    ]
