# Generated by Django 3.2.9 on 2023-02-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0004_buty_marka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buty',
            name='wybor',
        ),
        migrations.AddField(
            model_name='buty',
            name='rozmiar',
            field=models.IntegerField(choices=[(38, 'Male1 38'), (39, 'Male2 39'), (40, 'Srednie1 40'), (41, 'Srednie2 41'), (42, 'Duze1 42'), (43, 'Duze2 43')], default=40),
        ),
    ]
