# Generated by Django 3.2.9 on 2023-02-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0006_alter_buty_rozmiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='static')),
            ],
        ),
    ]
