# Generated by Django 3.2.9 on 2023-02-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0007_marki'),
    ]

    operations = [
        migrations.AddField(
            model_name='buty',
            name='cena',
            field=models.FloatField(default=299.99),
        ),
    ]
